baseURL: "https://github.com/computationalUncertaintyLab/complabweb" 
title: Computational Uncertainty Lab
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Lab members
          url: members/
          weight: 1

params:
    description: "Computational scientist,infectious diseases,forecasting"
    author: tom mcandrew
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: ""
          subtitle: "The computational uncertainty lab led by Prof. Thomas McAndrew aims to forecast the trajectory of infectious diseases by combining forecasts from computational models and human judgement. The lab is funded by the NIH, the Centers for Disease Control and Prevention, and the Council for State and Territorial Epidemiologists. The lab includes postdoctoral fellows, PhD candidates, Masters students, and undergraduates who study the intersection of human judgement, statistical forecasting and time series, and outbreak science."
          imageUrl: "compuncertlab.png"
          imageWidth: 300
          imageHeight: 300
          buttons:
            - name: Papers
              url: papers/
            - name: Courses
              url: courses/
            - name: Data
              url: data/
            - name: Books
              url: books/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Lab members
              url: members/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:mcandrew@lehigh.edu
        - name: Zoom
          url: https://lehigh.zoom.us/my/profmcandrew
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=JFIv-bIAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/computationalUncertaintyLab
        - name: YouTube
          url: https://www.youtube.com/@tomcm100

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "mcandrew@lehigh.edu (home)"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2